version: '3.2'
services:
  php:
    build:
      context: ./php
    ports:
      - 8000:8000
    volumes:
      - ${PROJECT_NAME}:/app:cached
      - composer-volume:/app/vendor
      - node-modules-volume:/app/node_modules
    command: ["php", "artisan", "serve", "--host", "0.0.0.0"]
    tty: true
    stdin_open: true
    depends_on:
      - db
  db:
    build:
      context: ./mysql
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 3310:3306
  yarn:
    build:
      context: ./yarn
    volumes:
      - ${PROJECT_NAME}:/app:cached
      - node-modules-volume:/app/node_modules
  mailhog:
    build:
      context: ./mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
volumes:
  composer-volume:
  node-modules-volume:
  mysql-volume:
