version: '3.7'
services:
  nginx:
    build:
      context: ./nginx
    ports:
      - ${NGINX_HTTP_PORT}:80
    depends_on:
      - php
    volumes:
      - ./${PROJECT_NAME}/public:/app/public:cached
      - ./${PROJECT_NAME}/storage:/app/storage:cached
  php:
    build:
      context: ./php
    volumes:
      - ./${PROJECT_NAME}:/app:cached
  db:
    build:
      context: ./mysql
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - ${DB_PORT}:3306
  yarn:
    build:
      context: ./yarn
    volumes:
      - ./${PROJECT_NAME}:/app:cached
      - node-modules-volume:/app/node_modules
  mailhog:
    build:
      context: ./mailhog
    ports:
      - "${SMTP_PORT}:1025"
      - "${HTTP_PORT}:8025"
volumes:
  mysql-volume:
  node-modules-volume:
